version: '2'
services:
  app: 
    build: ./
    volumes:
      - /home/andrei/workspace/csfnaicsf:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    hostname: mongo
    build: ../mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    restart: always